#!/bin/bash

# https://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

(echo "kev@peg.ear"; echo "kDuDsJkEkBvBtBmF") | nc ${SERVER} ${PORT} | tee "${DIR}/solve.out" | awk '{ print $4 }'
