#!/bin/bash

# https://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

run() {
	if [ -n "${SERVER}" ]; then
		nc "${SERVER}" "${PORT}"
	else
		"${DIR}/../../bin/runpeg" --plugin="${DIR}/../../bin/peg_rev_checker.so" "${DIR}/LicenseChecker.peg"
	fi
}

(echo "kev@peg.ear"; echo "kDuDsJkEkBvBtBmF") | run \
	| tee "${DIR}/solve.out" | awk '{ print $4 }'
