#!/bin/bash

# https://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

python3 "${DIR}/solve.py" 2>/dev/null \
	| tee "${DIR}/solve.out" | grep 'FLAG:' | tr ':' ' ' | awk '{ print $2 }'
