#ifndef ANSI_COLORS_H
#define ANSI_COLORS_H

#define ANSI_COLOR_BLACK 30
#define ANSI_COLOR_RED 31
#define ANSI_COLOR_GREEN 32
#define ANSI_COLOR_YELLOW 33
#define ANSI_COLOR_BLUE 34
#define ANSI_COLOR_MAGENTA 35
#define ANSI_COLOR_CYAN 36
#define ANSI_COLOR_WHITE 37
#define ANSI_COLOR_BRIGHT_BLACK 90
#define ANSI_COLOR_BRIGHT_RED 91
#define ANSI_COLOR_BRIGHT_GREEN 92
#define ANSI_COLOR_BRIGHT_YELLOW 93
#define ANSI_COLOR_BRIGHT_BLUE 94
#define ANSI_COLOR_BRIGHT_MAGENTA 95
#define ANSI_COLOR_BRIGHT_CYAN 96
#define ANSI_COLOR_BRIGHT_WHITE 97

#endif /* ANSI_COLORS_H */
