#!/bin/bash

# https://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

run() {
	if [ -n "${SERVER}" ]; then
		"${DIR}/../../bin/submitpeg" --server="${SERVER}" --port="${PORT}" "$1"
	else
		"${DIR}/../../bin/runpeg" --plugin="${DIR}/../../bin/peg_dev_checker.so" "$1"
	fi
}

run "${DIR}/uadd32_write.peg" 2>/dev/null \
	| tee "${DIR}/solve.out" | grep 'FLAG:' | tr ':' ' ' | awk '{ print $2 }'
